### ISSUE TITLE
Mutatio Logo - tagline, color and hi rez

### ISSUE THREAD

**Issue by lbrent2k** [lbrent2k/xyzzy#14]
@sreddy @kparikh

We need to be sure we are using best quality logo and we need to change tag line on logo.

Tagline should change from IT Solutions and Support Services to Transformative Data Solutions

**Comment by swarooo** [comment]
Done

**Comment by lbrent2k** [comment]
Is logo now too big on main banner?  Need to check with @kparikh

**Comment by swarooo** [comment]
if needed we can reduce the size of the logo. I just went with the original size of the logo
