### ISSUE TITLE
Career - Job posting and submission

### ISSUE THREAD

**Issue by lbrent2k** [lbrent2k/xyzzy#20]
@sreddy

We need to finalize posting of job openings and submission forms.

**Comment by swarooo** [comment]
Done, but we have to review the wordings and headings for all the job postings (need to be consistent).

**Comment by lbrent2k** [comment]
Data Analyst/Data Quality Specialist job is not up.

**Comment by swarooo** [comment]
there was some problem with the page link and i fixed it. It's working now. DONE
