### ISSUE TITLE
Google Analytics Tracking Code Snip

### ISSUE THREAD

**Issue by lbrent2k** [lbrent2k/xyzzy#35]
@sreddy  

Please insert on main page or use common include or template so it is on every page.

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67215743-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by swarooo** [comment]
Need the tracking code to include it in the main page.

**Comment by lbrent2k** [comment]
Tracking Code

UA-67210890-1

**Comment by swarooo** [comment]
Done
