### ISSUE TITLE
Text to insert in the Tell us about you   submission box

### ISSUE THREAD

**Issue by lbrent2k** [lbrent2k/xyzzy#9]
@sreddy

This is where you should tell us about yourself, provide a link to your Linkedin page or text of your resume.  You can also email your resume to careers@mutatioinc.com.

**Comment by swarooo** [comment]
Done

**Comment by lbrent2k** [comment]
The pre populated text needs to disappear when person starts typing.

**Comment by swarooo** [comment]
DONE. It's disappearing now.
